BBPATH := "${LAYERDIR}:${BBPATH}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "meta-sbom-cve"
BBFILE_PATTERN_meta-sbom-cve := "^${LAYERDIR}/"

BBFILE_PRIORITY_meta-sbom-cve = "10"

LAYERSERIES_COMPAT_meta-sbom-cve = "scarthgap"

LAYERDEPENDS_meta-sbom-cve = ""

INHERIT += "create-spdx"
SPDX_INCLUDE_SOURCES = "1"
SPDX_ARCHIVE_SOURCES = "1"
SPDX_ARCHIVE_PACKAGED = "0"

INHERIT += "cve-check"
