BBPATH := "${LAYERDIR}:${BBPATH}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "meta-project-setup"
BBFILE_PATTERN_meta-project-setup := "^${LAYERDIR}/"

BBFILE_PRIORITY_meta-project-setup = "10"

LAYERSERIES_COMPAT_meta-project-setup = "scarthgap"

LAYERDEPENDS_meta-project-setup = ""

DISTRO = "rpi"

RPI_USE_U_BOOT = "1"
#IMAGE_FSTYPES = "rpi-sdimg ext4.gz"
#PREFERRED_PROVIDER_u-boot-fw-utils = "libubootenv"

#DISTRO_FEATURES += "ipv4 wifi"
