apiVersion: v1
kind: Pod
spec:
  containers:  
    - name: yocto-builder
      image: docker.io/saxofon/yocto-builder:0.6
      command: ["tail", "-f", "/dev/null"]  
      imagePullPolicy: IfNotPresent
#      volumeMounts:
#      - mountPath: /cache
#        name: cache-volume
#      resources:  # limits the resources your build contaienr
#        requests:
#          memory: "32Gi"
#          cpu: "4"
#        limits:
#          memory: "32Gi"
#          cpu: "4"
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: node-data-dir    
          mountPath: /data  
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "scalable"
      effect: "NoSchedule"
    - key: "spotInstance"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "purpose"
      operator: "Equal"
      value: "scalable"
      effect: "NoSchedule"
    - key: "team"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: node-data-dir
      hostPath:
        path: /data
#    - name: cache-volume
#      awsElasticBlockStore:
#        volumeID: "vol-003aac349f608e970"
#        fsType: ext4
