apiVersion: v1
kind: Pod
spec:
  containers:  
    - name: yocto-builder
      image: docker.io/saxofon/yocto-builder:0.6
      command: ["tail", "-f", "/dev/null"]  
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: cache-volume
        mountPath: /cache
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: node-data-dir    
          mountPath: /data  
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: node-data-dir
      hostPath:
        path: /data
    - name: cache-volume
      awsElasticBlockStore:
        volumeID: "vol-003aac349f608e970"
        fsType: ext4
